 [functions]
   [functions.functions]
    external_node_modules = [
      "module-one",
      "module-two"
    ] 
  
[[redirects]]
  from = "/openai"
  to = "/.netlify/functions/openai"
  status = 200